# Generated by Django 3.1.1 on 2020-09-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Description',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name='book',
            name='Pages',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
