# Generated by Django 3.1.1 on 2020-09-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200906_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Pages',
        ),
    ]
