# Generated by Django 3.1.1 on 2020-09-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Pages',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
