# Generated by Django 3.1.1 on 2020-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Published_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Pages',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('HB', 'hOBBIT'), ('LOTR', 'GERTR')], max_length=36, null=True),
        ),
    ]
