# Generated by Django 3.1.1 on 2020-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200906_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
