# Generated by Django 3.1.1 on 2020-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20200909_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Size', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Published_date_Ap', models.DateField()),
                ('Images', models.ImageField(blank=True, upload_to='covers/')),
            ],
        ),
    ]
